{% set data = load_setup_py_data() %}

package:
  name: xhale
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - sphinx

test:
  imports:
    - xhale

about:
  home: https://github.com/QuantStack/xhale
  license: BSD
  license_family: BSD
  summary: 'convert sphinx inventory file into doxygen tag file'
  doc_url: 'https://xhale.readthedocs.io'

extra:
  recipe-maintainers: 'gouarin'