environment:
  matrix:
    - TARGET_ARCH: "x64"
      PYTHON_BUILD_RESTRICTIONS: "2.7*"
      CONDA_PY: "27"
      CONDA_INSTALL_LOCN: "C:\\Miniconda-x64"
      CONDA_BUILDS:  C:\\Miniconda-x64\conda-bld\win-64
    - TARGET_ARCH: "x64"
      PYTHON_BUILD_RESTRICTIONS: "3.5*"
      CONDA_PY: "35"
      CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"
      CONDA_BUILDS:  C:\\Miniconda35-x64\conda-bld\win-64
    - TARGET_ARCH: "x64"
      PYTHON_BUILD_RESTRICTIONS: "3.6*"
      CONDA_PY: "36"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
      CONDA_BUILDS:  C:\\Miniconda36-x64\conda-bld\win-64

platform:
  - x64

install:

  - cmd: SET PATH=%CONDA_INSTALL_LOCN%;%CONDA_INSTALL_LOCN%\Scripts;%PATH%

  - cmd: python setup.py install

# Skip .NET project specific build phase.
build: off

test_script:
  - xhale -p xtensor --url https://xtensor.readthedocs.io/en/latest/
